version: '3.8'

services:
  # PostgreSQLサービス（PGVector拡張機能付き）
  db:
    image: agnohq/pgvector:16
    container_name: pgvector
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5532:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai"]
      interval: 5s
      timeout: 5s
      retries: 5

  # SQLエージェントアプリケーション
  app:
    build: .
    container_name: sql_agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8509:8501"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
    name: pgvector_data
