version: '3.8'

services:
  # PostgreSQLサービス（PGVector拡張機能付き）
  pgvector:
    image: agnohq/pgvector:16
    environment:
      POSTGRES_DB: ai
      POSTGRES_USER: ai
      POSTGRES_PASSWORD: ai
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai"]
      interval: 5s
      timeout: 5s
      retries: 5

  # SQLエージェントアプリケーション
  sql_agent:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "${APP_PORT:-8509}:8501"
    depends_on:
      pgvector:
        condition: service_healthy
    env_file:
      - .env
      
volumes:
  pgdata:
    name: pgvector_data
